### ISSUE TITLE
undefined method `mac?

### ISSUE THREAD

**Issue by peng051410** [gantsign/development-environment#266]
When I install vagrant plugins,I got errors:
`There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: /Users/tomyli/github/tools/development-environment/Vagrantfile
Line number: 46
Message: undefined method `mac?'`

What should i do?

**Comment by freemanjp** [comment]
@peng051410 sorry for not getting to this earlier.

I think I've fixed this, but I don't have a mac to test it on, so let me know if you still have issues.

You can find the fix in the [1.15.0 release](https://github.com/gantsign/development-environment/releases/tag/1.15.0).

**Comment by peng051410** [comment]
Thank you!
