### ISSUE TITLE
Upgrade bento/ubuntu-18.04 to 20.04

### ISSUE THREAD

**Issue by istvano** [gantsign/development-environment#765]
Hi Guys,

First of all amazing project! I use it myself. I was wondering if you are planning to switch to 20.04? It has been around for a while now so I guess it would be safe to upgrade?

Thanks

**Comment by freemanjp** [comment]
Hi @istvano, try version [2.25.0](https://github.com/gantsign/development-environment/releases/tag/2.25.0) of this project. The default is still 18.04 for now, but you can update it to 20.04 in the `Vagrantfile` and it should now work.

**Comment by istvano** [comment]
Hi, 

Thanks for getting back to me! I will try it soon and let you know.

**Comment by istvano** [comment]
Hi,

thanks it looks great. I did upgrade to 20.04 by just changing the box and worked well.

config.vm.box = 'bento/ubuntu-20.04'

**Comment by freemanjp** [comment]
FYI: I've released version [2.27.0](https://github.com/gantsign/development-environment/releases/tag/2.27.0) of this project that makes Ubuntu 20.04 the default. I added the [Yaru Theme](https://github.com/ubuntu/yaru) to improve the desktop icons.
